[tools]
awscli = "latest"
eza = "latest"
fzf = "latest"
ripgrep = "latest"
zoxide = "latest"
bat = "latest"
fd = "latest"
delta = "latest"
shellcheck = "latest"
pre-commit = "latest"
# btop = "1.3.0"
k9s = "latest"
neovim = "latest"
rust = "latest"
cargo-binstall = "latest"
"cargo:atuin" = "latest"
"ubi:carapace-sh/carapace-bin" = { version = "latest", exe = "carapace" }
direnv = "latest"
"ubi:leg100/pug" = "latest"
"ubi:mvdan/sh" = { version = "latest", exe = "shfmt" }
usage = "latest"
lazygit = "latest"
