
[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

# github dark colorblind Alacritty Colors
# Default colors
# [colors.primary]
# background = '#0d1117'
# foreground = '#b3b1ad'

# # Normal colors
# [colors.normal]
# black = '#484f58'
# red = '#ff7b72'
# green = '#3fb950'
# yellow = '#d29922'
# blue = '#58a6ff'
# magenta = '#bc8cff'
# cyan = '#39c5cf'
# white = '#b1bac4'

# # Bright colors
# [colors.bright]
# black = '#6e7681'
# red = '#ffa198'
# green = '#56d364'
# yellow = '#e3b341'
# blue = '#79c0ff'
# magenta = '#d2a8ff'
# cyan = '#56d4dd'
# white = '#f0f6fc'

# [[colors.indexed_colors]]
# index = 16
# color = '#d18616'

# [[colors.indexed_colors]]
# index = 17
# color = '#ffa198'

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "MesloLGS NF"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "Buttonless"
dynamic_title = true
startup_mode = "Windowed"
opacity = 0.8
blur = true
option_as_alt = "Both"

[window.dimensions]
columns = 160
lines = 80

[window.padding]
x = 10
y = 10

[general]

live_config_reload = true
import = ["~/.config/alacritty/themes/themes/github_dark_colorblind.toml"]

[terminal]
